name: CI

on: [pull_request, push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: npm install, lint and test
      run: |
        npm install
        npm run lint
        npm run test:unit
